domain: "" #example.com
url: "" #https://example.com
baseurl: "/HubEx"

title: HubEx - Hub de projetos Extensionistas
email: brunomateus@ufc.br
author: Bruno Góis Mateus

lang: pt-br

plugins:
  - jekyll-seo-tag

color: "#13ccf9"
# disqus:
#   shortname: example-com
#
rrss:
  email: "example@example.cl"
  telegram: "https://t.me/"
  discord: "https://discord.com/"
